# FILE: 04_Diagnostic_Plots.ipynb
# CELL 2: Load Hierarchical Results & Define Cropping Fraction

# --- 1. Load Data ---
# Note: We now target the HIERARCHICAL file generated by the updated Notebook 02
FINAL_RESULTS_FILE = "results/FINAL_HIERARCHICAL_metrics.parquet"
YLD_FILE = "data/processed/icrisat_yield_area_irrig_4crops_long_2000_2017.csv"
DISTRICTS_GEO_FILE = "data/processed/districts_joined.gpkg"

try:
    results_df = pd.read_parquet(FINAL_RESULTS_FILE)
    yld = pd.read_csv(YLD_FILE)
    districts_gdf = gpd.read_file(DISTRICTS_GEO_FILE)

    print(f"[✓] Loaded Results: {len(results_df)} district-models.")
    print(f"    Columns available: {results_df.columns.tolist()}")

except FileNotFoundError as e:
    raise SystemExit(f"Missing File: {e}")

# --- 2. Define The Filter Metric: Cropping Fraction ---
# (Replaces the old 'Production Density' logic)
def get_cropping_fraction(crop_name):
    """
    Calculates the fraction of district area dedicated to the crop.
    Metric: (Average Harvested Area) / (District Shapefile Area)
    """
    # 1. Get Average Harvested Area (ha)
    crop_data = yld[yld['crop'] == crop_name].copy()
    avg_area = crop_data.groupby('Dist Code')['total_area_1000ha'].mean().reset_index()
    avg_area['harvested_ha'] = avg_area['total_area_1000ha'] * 1000

    # 2. Get District Total Area (ha) - Using Equal Area Projection
    dist_proj = districts_gdf.to_crs(epsg=6933)
    dist_areas = dist_proj[['Dist Code', 'geometry']].copy()
    dist_areas['district_total_ha'] = dist_proj.geometry.area / 10000

    # 3. Merge
    merged = avg_area.merge(dist_areas, on='Dist Code', how='inner')
    merged['cropping_fraction'] = merged['harvested_ha'] / merged['district_total_ha']

    # Clip to 1.0 to handle data noise
    merged['cropping_fraction'] = merged['cropping_fraction'].clip(upper=1.0)

    return merged[['Dist Code', 'cropping_fraction']]

print("[✓] Helper function 'get_cropping_fraction' defined.")